name: farmers_network
description: farmers_network.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.9+10

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    cupertino_icons: ^1.0.3
    custom_switch: ^0.0.1
    flutter:
        sdk: flutter
    flutter_launcher_icons: ^0.9.2
    flutter_switch: ^0.3.2
    font_awesome_flutter: ^9.2.0
    #carousel_slider: ^4.0.0
    hexcolor: ^2.0.5
    http: ^0.13.4
    sizer: ^2.0.15
    otp_text_field: ^1.1.1
    shared_preferences: ^2.0.7
    cached_network_image: ^3.2.0
    
    charts_flutter:
        git:
            url: https://github.com/google/charts.git
            path: charts_flutter
    video_player: ^2.2.3
    flutter_rating_bar: ^4.0.0
    table_calendar: ^3.0.3
    intl_phone_number_input: ^0.7.0+2
    flutter_staggered_grid_view: ^0.4.0
    comment_box: ^0.0.16
    image_picker: ^0.8.4+5
    flutter_datetime_picker: ^1.5.1
    like_button: ^2.0.4
    comment_tree: ^0.3.0
    intl: ^0.17.0
    flutter_markdown: ^0.6.8
    carousel_slider: ^4.0.0
    open_file: ^3.2.1
    pdf: ^3.7.1
    printing: ^5.7.2
    url_launcher: ^6.0.20
    introduction_screen: ^3.0.0
    google_fonts: ^2.3.0
    date_field: ^3.0.0
    

dev_dependencies:
    flutter_test:
        sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
    image_path: "assets/icon/icon.png"
    android: true
    ios: true
# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true


    fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
          - asset: assets/fonts/Poppins-Medium.ttf

    # To add assets to your application, add an assets section, like this:
    assets:
        - logo.jpg
        - assets/images/home.png
        - assets/images/farmer.jpeg 
        - assets/images/dlogo.png
        - assets/images/trade.png
        - assets/images/forums.png 
       
        - assets/images/Dallan_farm.jpg
        - assets/images/serviceProvider.jpeg
        - assets/images/events.png
      
        - assets/images/market.png
        - assets/images/Weather.png
        - assets/images/weatherbackground.jpg
        - assets/images/login.png
        - assets/images/app.jpg

        - assets/images/report.png
#        - assets/images/serviceProvider.png
        - assets/images/developmentPartners.png

        - assets/images/resources.png
   
        - assets/images/logo.png
        - assets/images/offtake.png
        - assets/images/landing.jpg
        - assets/images/Partners.png
        - assets/images/Consultant.png
        - assets/images/sky.jpeg
     
        - assets/images/ok.png
        - assets/images/Business.png
        - assets/images/chat.png 
        - assets/images/login.png
        - assets/images/reports.png
        - assets/images/shop.png 
       
        - assets/images/services_providers_icon.png
        - assets/images/ProfileHolder.png
        - assets/video.mp4
        - PrivacyPolicy.md

        - assets/images/siteLogo.jpeg
        - assets/images/siteID.jpeg
        - assets/images/background.jpeg
        - assets/images/logo3.jpg
        - assets/images/app.jpg
        - assets/images/fcbk.jpeg
        - assets/images/google.jpeg
   
   
        
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
module:
    androidX:true # Add this line.
